### ISSUE TITLE
Latest release is missing the `v`

### ISSUE THREAD

**Issue by bmaupin** [coverallsapp/github-action#100]
This is pretty trivial so feel free to close it, but the latest release is `1.1.3` whereas all the other release tags start with a `v`, e.g. `v1.1.2`.

Thanks!

**Comment by hartwork** [comment]
My vote for adding a copy named `v1.1.3` too, e.g. because I am worried that mixing schemes will confuse GitHub Dependabot thank you!

CC @afinetooth

**Comment by jrfnl** [comment]
Could this be why the below does not work ?
```
uses: coverallsapp/github-action@v1
```

It is generally strongly recommended to always "lock" actions to a version to prevent CI builds to unexpectedly start failing due to a new major of an action having been released. That is currently not possible with this action.

**Comment by jrfnl** [comment]
Related to / duplicate of #94

**Comment by hartwork** [comment]
@jrfnl `@v1` is a moving Git tag that those repos keep moving whenever they crate a new `v1.x.y` tag. Ideally, Git tags never move, so it's arguably a hack. The reason it doesn't work here is because there is no tag named `v1` at https://github.com/coverallsapp/github-action/tags .

**Comment by jrfnl** [comment]
@hartwork Thanks for the explanation. Sounds like something which should be solved.

**Comment by prescottprue** [comment]
@jrfnl I'm not seeing any CI in the repo currently you are implementing in a Actions workflow, I've done that with a simple step to push the change to a branch after releasing (this example grabs version from the package.json since you seem to be managing that manually):


```yaml
      - name: Push updates to branch for major version
        # If a new version is published, i.e. v1.2.3 then this step will update
        # branch "v1" to this commit.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v$(cat package.json | jq '.version')
```

Using semantic-release like [Cypress does with their Github Action](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml#L46) makes it even cleaner since you can detect if a version was released:

```yaml
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push updates to branch for major version
        # If a new version is published, i.e. v1.2.3 then this step will update
        # branch "v1" to this commit.
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}
```
