### ISSUE TITLE
Action expects `lcov` to be run in `runner` environment/file system.

### ISSUE THREAD

**Issue by zfields** [coverallsapp/github-action#103]
If unit-tests and `lcov` are run inside a container, they end up with a path like, `/github/workspace/src/SourceFile.cpp`.
However, if the unit-tests and `lcov` are executed using the `run:` tag (natively in the `runner`), they have a path like,  `/home/runner/work/<repo>/<repo>/src/SourceFile.cpp`.

I was unable to discover an option that could be passed to `lcov` to satisfy the Coveralls GitHub action requirement. I was able to introduce a workflow step to workaround this issue (shown below), but my goal would be to remove this step in favor of an updated Coveralls acton.

```yaml
- name: Coveralls Action Bug Workaround
  id: coveralls_bug_workaround
  run: sudo sed -i 's/github\/workspace/home\/runner\/work\/<repo>\/<repo>/g' ./coverage/lcov.info
```

My expectation is that the Coveralls GitHub action would be compatible with tests executed in both native and docker actions.
