### ISSUE TITLE
[Question] Clover upload supported?

### ISSUE THREAD

**Issue by mimmi20** [coverallsapp/github-action#12]
Is it possivble to upload a clover coverage report using this action?

**Comment by teohhanhui** [comment]
You can try https://github.com/cedx/coveralls.php

Example on GitHub Actions:

```yaml
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require cedx/coveralls
          coveralls build/logs/phpunit/clover.xml
```

**Comment by mimmi20** [comment]
I will stay with the shell script.

**Comment by twinh** [comment]
Hello, You may try this:

https://github.com/twinh/php-coveralls#github-actions

Add a new step after phpunit generate coverage report.

```yaml
- name: Upload coverage results to Coveralls
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    composer global require twinh/php-coveralls
    php-coveralls --coverage_clover=build/logs/clover.xml -v
```
