### ISSUE TITLE
Action should support the global working-directory

### ISSUE THREAD

**Issue by dominikwilkowski** [coverallsapp/github-action#122]
Github has a global that it supports called [`working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun). This enables you to run an action in a specified working directory.
This action seems to ignore it which leads to thing like this:

```yaml
coverage-nodejs:
  defaults:
    run:
      working-directory: ./nodejs

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn jest --coverage
    - run: tail ./coverage/lcov.info
    #      ^-- this outputs the actual last few lines of the lcov.info successfully
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./nodejs/coverage/lcov.info
        #               ^-- ignoring working-directory here
        base-path: ./nodejs
        #          ^-- duplication of working-directory perhaps?
```
