### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by sschmid** [coverallsapp/github-action#132]
Running the GitHub action results in a warning:

```
- name: Coveralls
  uses: coverallsapp/github-action@master
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: "coverage/lcov.info"
```

```
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: coverallsapp/github-action
```

For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
