### ISSUE TITLE
Please provide a floating tag that indicates the latest major version

### ISSUE THREAD

**Issue by denisa** [coverallsapp/github-action#140]
Many actions provide ‘v1’, rarely `v1.1`, tags that follow the latest major, minor versions.

This simplify the maintenance of the users’ GitHub action flows, as user can then write
```
    - name: Send coverage
      uses: coverallsapp/github-action@1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
```
and benefit from the latest improvements
