### ISSUE TITLE
Use action for report generated by php-coveralls/php-coveralls

### ISSUE THREAD

**Issue by Smolevich** [coverallsapp/github-action#15]
I try to use this action for php project
Report generated by php-coveralls/php-coveralls and has format xml
I add 
```
- name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./clover.xml
```
Step was failed with error `'error from lcovParse: ' 'Failed to parse string'`

**Comment by Smolevich** [comment]
@nickmerwin, can you answer me?

**Comment by ad-m** [comment]
Similar issue for Python.

**Comment by teohhanhui** [comment]
For PHP, you can try https://github.com/cedx/coveralls.php

Example on GitHub Actions:

```yaml
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require cedx/coveralls
          coveralls build/logs/phpunit/clover.xml
```

**Comment by s-weigand** [comment]
Would be nice to also have at least xml support.

**Comment by teohhanhui** [comment]
> Would be nice to also have at least xml support.

I think this is what this issue is about. Clover XML format support.

**Comment by s-weigand** [comment]
In my case it is `coverage.py`, sadly the clients don't support `gh actions` yet.
But [`coveralls-python support json output`](https://coveralls-python.readthedocs.io/en/latest/usage/multilang.html), so you could basically shove the json payload into `Coveralls GitHub Action`.
But `*.xml` is the most common format I guess, also I can't find a tool that converts any [format supported by `coverage.py`/`pytest-cov`](https://pytest-cov.readthedocs.io/en/latest/reporting.html) to `lcov.info` .

**Comment by twinh** [comment]
Hello, for PHP, You may try this:

https://github.com/twinh/php-coveralls#github-actions

Add a new step after phpunit generate coverage report.

```yaml
- name: Upload coverage results to Coveralls
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    composer global require twinh/php-coveralls
    php-coveralls --coverage_clover=build/logs/clover.xml -v
```
