### ISSUE TITLE
v2 doesn't work

### ISSUE THREAD

**Issue by flatcap** [coverallsapp/github-action#159]
According to the `README.md` v2 is,

> It is a pre-release but will become the main supported version soon.

This is my working **v1** config:

```
- name: Coveralls
  uses: coverallsapp/github-action@master
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: coverage.info
```

---

I gave **v2** a go:

```
- name: Coveralls
  uses: coverallsapp/github-action@v2
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    file: coverage.info
```

**Failed:**
> 📄 Using coverage file: coverage.info
> ⚠️ Coverage reporter does not yet know how to process this file: coverage.info

[Action log](https://github.com/neomutt/neomutt/actions/runs/4511246142/jobs/7943169781)

---

The docs say that the `file` parameter is optional:

```
- name: Coveralls
  uses: coverallsapp/github-action@v2
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Failed:**
> Nothing to report

[Action log](https://github.com/neomutt/neomutt/actions/runs/4511317571/jobs/7943324941)

---

Let's try the old parameter, just in case:

```
- name: Coveralls
  uses: coverallsapp/github-action@v2
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: coverage.info
```

**Failed:**
> 📄 Using coverage file: coverage.info
> ⚠️ Coverage reporter does not yet know how to process this file: coverage.info

[Action log](https://github.com/neomutt/neomutt/actions/runs/4511342705/jobs/7943380191)

---

What am I doing wrong?
Thanks

**Comment by flatcap** [comment]
@Xyaneon is seems that we're missing the `format` param:

This works for me:
```
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.info
        format: lcov
```

Thanks to @snototter who figured it out.
