### ISSUE TITLE
Mono repo + Windows absolute paths?

### ISSUE THREAD

**Issue by dcharkes** [coverallsapp/github-action#169]
When generating coverage, the `LCOV` files contain absolute paths. How this Coveralls convert these to relative paths?

We have a matrix build that uploads coverage for various builds:

```yaml
[ ... ]
      - name: Upload coverage
        uses: coverallsapp/github-action@67662d24394fd74bffcf7b462d1b432814159afd
        with:
          flag-name: ${{ matrix.package }}-${{ matrix.os }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
```

and in the end we signal we are done:

```yaml
  coverage-finished:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage
        uses: coverallsapp/github-action@67662d24394fd74bffcf7b462d1b432814159afd
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
```

In the coveralls UI, the MacOS/Linux paths are relative to current working directory, but this doesn't seem the case for the Windows build:

* https://coveralls.io/builds/59339135

An older build seemed to work, but as far as I can see nothing changed in the configuration 🙊 

* https://coveralls.io/builds/59308648

For reference, the GitHub workflow configuration:

* https://github.com/dart-lang/native/blob/983ef4b309021a448b2067f9c30be7d66b5ff84d/.github/workflows/dart.yaml

Upon inspection, all LCOV files we produce contain absolute paths everywhere.
That must mean there is some logic somewhere within Coveralls to convert these to relative paths. How does that logic work?

Should we be emitting LCOV files with relative paths instead to avoid these kinds of issues?
Or am I doing something else wrong in the configuration?
Feel free to leave a comment on https://github.com/dart-lang/native/pull/16.
