### ISSUE TITLE
Multiple Coverage files not being merged when uploaded

### ISSUE THREAD

**Issue by StuartFerguson** [coverallsapp/github-action#18]
In my Github actions workflow I am running 3 dotnet test commands as follows

`  dotnet test "TestsProject1.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov1.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"

  dotnet test "TestsProject2.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov2.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"

  dotnet test "TestsProject3.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov3.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"`

Each of the steps generates its own coverage file.

In my work flow I have a step to upload each of the coverage files as follows (where N in the file name relating to the test step):  

- name: Upload Code Coverage 
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: lcovN.info   

I then have a coverall finished step as follows:

- name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

However what appears to be happening is the 3 files are being uploaded as 3 seperate jobs but the coverage is not being aggregated (i.e. the results I see are from the lcov3.info file).

Is there a way that the files can be uploaded in a single job or is there a way to get the results aggregated?

**Comment by jlabeit** [comment]
Hey,
I am having the same issue. I am using a matrix to run multiple tests suites and the notify coveralls with `parallel-finished: true`:
```yml
 checks:
    needs: [checks-modules]
    strategy:
      matrix:
        service:
        - Service/a
        - Service/b
        - Service/c
    runs-on: ubuntu-latest
    steps:
    - name: Test
     run: run test in ${{ matrix.service }}
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./${{ matrix.service }}/coverage/lcov.info

coveralls-finished:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
```

In coveralls the coverage from all the different jobs show up but the coverage is not aggregated.
