### ISSUE TITLE
Version 0.6.11 broke our CI

### ISSUE THREAD

**Issue by mcallegari** [coverallsapp/github-action#211]
Hi, we're having CI failures since a couple of days.
Looks like the new version doesn't like our coverage.info file anymore

Working CI
![image](https://github.com/coverallsapp/github-action/assets/2951337/e493ea70-8385-4693-b5fa-a8e77b4bf610)

Broken CI
![image](https://github.com/coverallsapp/github-action/assets/2951337/c2ee645e-934c-48b6-98ba-b8502a62ed83)

Our Actions YAML
```
      - name: Coveralls
        if: ${{ startsWith( matrix.task, 'coverage') }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/coverage.info
          format: lcov
```

Do we have to change any parameter with the new version or is this a bug?
Thanks!
