### ISSUE TITLE
`v2` tag doesn't match latest `v2.3.0` tag

### ISSUE THREAD

**Issue by kurtmckee** [coverallsapp/github-action#222]
Please update the `v2` tag in the repo to point to the latest release (`v2.3.0` as I write this).

It's currently pointing to the previous release SHA.

> ![image](https://github.com/user-attachments/assets/cbb8f330-4759-4ea9-ad5d-60ed87baddee)

Thanks!

**Comment by afinetooth** [comment]
Thanks @kurtmckee. We'll get that handled asap.

**Comment by kurtmckee** [comment]
The `v2` tag is drifting further, and now appears to be missing some recent bug fixes and improvements.

**Comment by afinetooth** [comment]
@kurtmckee Thanks for the update. 

I have not been able to reproduce this drift in action version, so I’m missing something.

Can you help me with a little more context, such as your CI config for your Coveralls step(s), and your CI build log, at least the portion pertaining to Coveralls?

If you could set `debug: true` that would be ideal since it turns on `set -x` style debugging (at least in the latest versions).

I’ve added tests to the action now, which you can see in later versions with their results. This is what I will do, but you are welcome to as well: We can start a new PR, replicate your config details in the `.gitHub/workflows/test.yml` workflow there, and see if we can reproduce.

**Comment by kurtmckee** [comment]
This is what I'm referring to:

> ![image](https://github.com/user-attachments/assets/2c9ee0bc-c1dd-4b30-ae6c-b7ba9f1f37dd)

It is common practice for repos hosting GitHub actions to force major-version git tags (like `v2` in the screenshot above) to match the latest version tag. This allows most repos to reference the action using the syntax `coverallsapp/github-action@v2` and use the latest major version of the action.

When `v2.3.2` was released yesterday, the `v2` tag should have been updated to point to the same commit SHA (`43f11c4`), but it hasn't been; it's still pointing to the `v2.2.3` commit SHA, released over a year ago.

This is a significant gap in the release process, and it's what this issue is reporting.

**Comment by kurtmckee** [comment]
For example, if you look at the [CI workflow in coverallsapp/coverage-reporter](https://github.com/coverallsapp/coverage-reporter/blob/master/.github/workflows/ci.yml#L17), you'll observe this line:

```yaml
    - uses: actions/checkout@v4
```

Then, [checking the tags in the actions/checkout repository](https://github.com/actions/checkout/tags), you'll see that their `v4` tag points to their latest v4 release, v4.2.1:

> ![image](https://github.com/user-attachments/assets/baa64ad9-492d-47f2-ad1b-e6f08e99e7dc)

I'm requesting that the coverallsapp team continuously update the `v2` git tag as new versions are released. This is the standard practice for repos hosting GitHub actions.

**Comment by afinetooth** [comment]
Whoah, I've never seen that before, where a tag for `v2` appears after a subsequent version, like `v2.2.2`. 

Thank you for the examples and screenshots! Apologies, I think I just wasn't able to "see" that before.

I'm relatively new at managing these releases. Let me figure out how to fix that...

**Comment by kurtmckee** [comment]
It's definitely a deviation from the common git practice "immutable repo history" but it's a very specific deviation for GitHub action repos. :+1:

**Comment by afinetooth** [comment]
@kurtmckee this should be fixed.

Please let me know if it appears otherwise for you.

**Comment by kurtmckee** [comment]
Sure does! Thanks!

I don't know if your release process is scripted or documented, but I recommend adding that `v2` tag update step in, if possible.

Thanks for your work on this! :partying_face:

**Comment by afinetooth** [comment]
>  I recommend adding that v2 tag update step in, if possible.

That's a good recommendation. I am just looking for a common pattern to do that. Are you familiar with one?

**Comment by afinetooth** [comment]
I found a good example, so I'm good there! ^^

Gonna close this one. Thanks for your patience!!

**Comment by afinetooth** [comment]
In case it's helpful to anyone with a similar issue, here's a generic workflow to make sure the **major version tag** (ie. `v2`) (the "floating" tag) always points to the **latest release** (latest subversion of the major version, ie. `v2.3.2`).

Will work for any major version (`v2`, `v3`, `v4`, etc.):

```
# update-major-version-tag.yml
name: Update Major Version Tag

on:
  release:
    types: [published]

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Major Version
        id: extract_major_version
        run: |
          # Extract the major version part (e.g., "v2" from "v2.3.1")
          echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          major_version=$(echo "${{ github.event.release.tag_name }}" | grep -oE "^v[0-9]+")
          echo "major_version=$major_version" >> $GITHUB_ENV

      - name: Update Major Version Tag
        run: |
          git fetch --tags
          git tag -f ${{ env.major_version }} ${{ github.event.release.tag_name }}
          git push origin ${{ env.major_version }} --force
```
