### ISSUE TITLE
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}

### ISSUE THREAD

**Issue by changhuixu** [coverallsapp/github-action#23]
First time try this action. Not sure what's wrong...
```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: ./uiowa.DelimitedDataHelper.Tests/TestResults/coverage.info
    coveralls-endpoint: https://coveralls.io
  env:
    DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.0.100/x64
Using lcov file: ./uiowa.DelimitedDataHelper.Tests/TestResults/coverage.info
##[error]Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
##[error]Node run failed with exit code 1
```

The project url in coveralls.io is https://coveralls.io/github/changhuixu/DelimitedDataFileHelper
Is there anyone could help me?
Thank you.

**Comment by bboe** [comment]
I got this error when I didn't accurately set the github-token field:

```
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ntwb** [comment]
Having a similar issue @stylelint https://github.com/stylelint/stylelint/pull/4504

It works on the _pull request_ job, but not the _push_ job:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1016458/71787286-fc406780-3069-11ea-9068-dcf3030c5819.png">

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1016458/71787307-3447aa80-306a-11ea-81b4-74977f1c6d8f.png">
<img width="715" alt="image" src="https://user-images.githubusercontent.com/1016458/71787312-43c6f380-306a-11ea-8ee4-7832865e437d.png">

Our config is here: 

https://github.com/stylelint/stylelint/blob/master/.github/workflows/nodejs.yml#L109-L120

```yaml
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true
        path-to-lcov: ./.coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
```
