### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED] Package subpath './v4' is not defined by "exports"

### ISSUE THREAD

**Issue by peppescg** [coverallsapp/github-action#234]
I had unknown coverage so I tried to run locally coveralls with `./coverage/lcov.info`, but I got a node error related to exports not defined on a package.
Do you have any insights?
Node LTS  `v20.18.0`
____

```
node:internal/modules/cjs/loader:641
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /Users/******/node_modules/uuid/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/******/node_modules/request/lib/auth.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by afinetooth** [comment]
@peppescg What [Coveralls Integration](https://docs.coveralls.io/integrations) are you using? The fact that you're posting in this forum suggests you're using our [Official Integration](https://docs.coveralls.io/integrations#official-integrations), the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action), but that shouldn't be throwing a Node error, so are you also employing another integration, such as a [Language Integration](https://docs.coveralls.io/integrations#language-integrations) like [node-coveralls](https://docs.coveralls.io/javascript) (outdated)?

Or are you using `v1` of our GitHub Action, which uses [node-coveralls](https://github.com/nickmerwin/node-coveralls) under-the-hood?:

```
    - name: Coveralls
      uses: coverallsapp/github-action@v1
```

If so, I'd recommend using `@v2`:

```
    - name: Coveralls
      uses: coverallsapp/github-action@v2
```

Can you please share your config, your original response from the GitHub Action / POST to the Coveralls API, and any other details on your use case?

Can you also please supply the command you used to "run locally coveralls"?

Thanks.

**Comment by peppescg** [comment]
Hi @afinetooth , so I am using the [GH action](https://github.com/marketplace/actions/coveralls-github-action), pointed to the last commit. 
My issue is that I see from the actions that everything is ok, but I am not able to see the coverage in coveralls, and also I don't see it as PR comment. I enabled the PR comments feature through settings.

```
 name: Send coverage to Coveralls
        uses: coverallsapp/github-action@1134c89e4bf10443bf8f0ec69640b667cfd91041 #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
```

**Comment by afinetooth** [comment]
Hi @peppescg.

OK, just FYI, that commit is not the latest commit, per [commit history](https://github.com/coverallsapp/github-action/commits/main/) / [releases](https://github.com/coverallsapp/github-action/releases), and the version you're pointing to with that commit is actually `v2.3.1` and not `v2.3.0` (per your comment).

Also, per this config:

```
 name: Send coverage to Coveralls
        uses: coverallsapp/github-action@1134c89e4bf10443bf8f0ec69640b667cfd91041 #v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
```

You're using an outdated input option, `path-to-lcov`, which was retired with `@v1` in lieu of [`file` (or `files`)](https://github.com/marketplace/actions/coveralls-github-action#:~:text=.%20More%20Info-,file,your%20test%20suite.%20Example%3A%20files%3A%20coverage/test1.lcov%20coverage/test2.lcov,-format).

So the first thing to do is try that.

I'd also recommend just calling the action with `@v2` which will grab the latest release in the `2.x.x` series, so:

```
 name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage/lcov.info
```

If you're still having an issue, please share the response from your CI build log.

Also, if you are meaning to run the underlying integration that the github action installs, it's no longer `node-coveralls` (aka. `coveralls npm package`), it's now a cross-platform binary called the [Universal Coverage Reporter](https://docs.coveralls.io/integrations#universal-coverage-reporter), which you can find here: https://github.com/coverallsapp/coverage-reporter

Usage instructions for coverage-reporter are here:
https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#usage

Per that, the equivalent command, once you're sure coverage-reporter has been successfully downloaded and installed in your runner environment, is:

```
coveralls report coverage/lcov.info
```

Or possibly:

```
./coveralls report coverage/lcov.info
```

And you'l probably need to include your `repo_token`:

```
./coveralls report coverage/lcov.info --repo-token=<your_repo_token>
```
