### ISSUE TITLE
Unexpected input(s) 'build-number'

### ISSUE THREAD

**Issue by dynobo** [coverallsapp/github-action#246]
Is the `build-number` input, that's listed in the README, deprecated, or am I doing something wrong?

Sidenote: Some other inputs from the README are also not part of the "valid inputs" listed in the warning: `coverage-reporter-version`, `coverage-reporter-platform`. Didn't check, if they are working, though.

Step definitions
```yaml       
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@release/v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.os }}
          path-to-lcov: coverage.lcov
          build-number: ${{ github.run_number }}
          parallel: true

# ...

      - name: Coveralls Finished
        uses: coverallsapp/github-action@release/v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          build-number: ${{ github.run_number }}
```

Output of the final step (warning also appears in the parallel steps):
```
Warning: Unexpected input(s) 'build-number', valid inputs are ['github-token', 'path-to-lcov', 'file', 'files', 'format', 'flag-name', 'parallel', 'parallel-finished', 'carryforward', 'coveralls-endpoint', 'allow-empty', 'base-path', 'git-branch', 'git-commit', 'compare-ref', 'compare-sha', 'debug', 'measure', 'fail-on-error']
Run coverallsapp/github-action@release/v2
Run mkdir -p ~/bin/
coveralls-linux.tar.gz: OK
Run coveralls done   
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.15

⚠️ git log -1 --pretty=format:'%H%n%aN%n%aE%n%cN%n%cE%n%s' (return code 128)
⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
✅ API Response: {"done":true,"url":"https://coveralls.io/builds/73262341","jobs":0}
- 💛, Coveralls
```
