### ISSUE TITLE
No clear examples for rails project

### ISSUE THREAD

**Issue by mcampo84** [coverallsapp/github-action#29]
I'm new to Ruby on Rails, Github Actions _and_ Coveralls, and I can't seem to get this github action working. It doesn't seem to be able to find the coverage report file after I run rspec tests.

My .coveralls.yml file looks like this:
```name: Ruby

on: [push, "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Run rspec
      run: |
        gem install bundler
        bundle install
        bundle exec rspec spec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

What am I missing?

**Comment by clh161** [comment]
same problem to yours
I tried to add `path-to-lcov` but no luck
```yaml
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/.resultset.json
```
I wonder if Rails is not supported

**Comment by stephaneliu** [comment]
Overalls expects a consolidated lcov.info file.

`# Gemfile
gem "simplecov-lcov"

# spec_helper.rb
if ENV["COVERAGE"]
  require "simplecov"
  require "simplecov-lcov"

  SimpleCov.start "rails" do
    if ENV["CI"]
      SimpleCov::Formatter::LcovFormatter.config do |config
        config.report_with_simgle_file = true
        config.lcov_file_name = "lcov.info"
    else
      SimpleCov::Formatter::HTMLFormatter
    end
end

# test.yml
- name: Run test
   ...
   run: |
     ...
     COVERAGE=true CI=true DISABLE_SPRING=true bundle exec rspec spec
- name: Coveralls 
  uses: coverallsapp/github-action@master
  with:
    github-tocken: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: "./coverage/lcvo/lcov.info"`

**Comment by jfo84** [comment]
Here is some cleaned up code of @stephaneliu, etc.

spec_helper.rb
```
if ENV['COVERAGE'] == 'true'
  require 'coveralls'
  require 'simplecov'
  require 'simplecov-lcov'

  if ENV['CI'] == 'true'
    SimpleCov::Formatter::LcovFormatter.config do |config|
      config.report_with_single_file = true
      config.lcov_file_name = 'lcov.info'
    end

    SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
      SimpleCov::Formatter::LcovFormatter,
      Coveralls::SimpleCov::Formatter
    ])
  else
    SimpleCov.formatter = SimpleCov::Formatter::HTMLFormatter
  end

  SimpleCov.start('rails')
end
```

ci.yml
```
- name: Coveralls 
  uses: coverallsapp/github-action@master
  with:
    github-tocken: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: "./coverage/lcov/lcov.info"
```

Gemfile
```
  gem 'simplecov', require: false
  gem 'simplecov-lcov', require: false
  gem 'coveralls_reborn', '~> 0.18.0', require: false
```

You will need [this library](https://github.com/tagliala/coveralls-ruby-reborn) as well since the original is unmaintained.

Cheers
