### ISSUE TITLE
Add support for glob patterns in path-to-lcov 

### ISSUE THREAD

**Issue by aalmada** [coverallsapp/github-action#36]
Would it be possible to add support for glob patterns in `path-to-lcov`?

The tool stack I'm using generates the `lcov` inside a folder named as a GUID. Not having to specify it would be very helpful.

``` yml
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./TestResults/**/coverage.info 
```

**Comment by aaomidi** [comment]
Definitely would be useful. Might make a PR for this.

**Comment by kevinoid** [comment]
I agree this would be a useful feature.  For reference, a GUID directory name is unavoidable with Coverlet on .NET due to coverlet-coverage/coverlet#500.  Coverlet is a popular coverage framework that may be worth supporting well.

Until/Unless it is implemented, a workaround I'm using is to pass the lcov path as a step output:

```yaml
- name: Get path to lcov file
  id: get_lcov_path
  shell: bash
  run: printf '::set-output name=lcov_path::%s\n' TestResults/*/coverage.info
- name: Upload coverage to Coveralls
  uses: coverallsapp/github-action@master
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    path-to-lcov: ${{ steps.get_lcov_path.outputs.lcov_path }}
```

Where `run: printf ...` could be replaced with any command(s) which print the [`::set-output` workflow command](https://docs.github.com/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) with the desired path.  Note that if multiple `::set-output` lines are printed, all but the last are ignored.
