### ISSUE TITLE
So short documentation

### ISSUE THREAD

**Issue by pbelskiy** [coverallsapp/github-action#49]
Hello, I am trying to configure coveralls with parallels builds using GitHub Actions with your documentation: https://docs.coveralls.io/parallel-build-webhook

So, As I understand by coverage isn't published due my builds is in pending state (waiting web hook?)

I've added at last step (finish section) I just call curl with my report token, and it's returned 404 error, how to configure it properly and could you please add such steps into your documentation

```yaml
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      run: |
        curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls }}
```

Example: https://github.com/pbelskiy/aiojenkins/actions/runs/106594356

**Comment by pbelskiy** [comment]
Solved, it's should be like this:

```yaml
  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      run: |
        curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls }} -d "payload[build_num]=${{ github.sha }}&payload[status]=done"
```

So, payload missed in top of documentation.

PS: also strange that this repo support only lcov files and don't accept standard json, for example python's coverage generated by pytest isn't pushed using this GitHub action -> lcov file not found.
