### ISSUE TITLE
flag-name mentioned in README; not declared in action.yml

### ISSUE THREAD

**Issue by cspotcode** [coverallsapp/github-action#50]
README talks about it here:
https://github.com/coverallsapp/github-action#inputs

action.yml does not declare it:
https://github.com/coverallsapp/github-action/blob/master/action.yml

Github Actions shows a validation error if you try to pass `flag-name`:
```
Unexpected input 'flag-name', valid inputs are ['github-token', 'path-to-lcov', 'parallel', 'parallel-finished', 'coveralls-endpoint', 'base-path']
```
![image](https://user-images.githubusercontent.com/376504/82154882-e1170d00-983e-11ea-8071-ab11b13d1855.png)

**Comment by twinh** [comment]
For someone stop here, you may use env `COVERALLS_FLAG_NAME` instead.

see https://github.com/coverallsapp/github-action/blob/348853a262cc37fa2f8abe2827729d193cbb00dc/src/run.ts#L29

example

```yaml
      - name: Coveralls
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.test_number }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
```
