### ISSUE TITLE
422 Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by kennethtran93** [coverallsapp/github-action#51]
It was fine about 3 hours ago...not sure what I'm doing wrong or is it a server issue?

3 hours ago...I was still using 1.0.1, and it was still successful.  Once it failed with this error, I tried to use the updated v1.1.1 version but still same result.   The repo is open source, and I only used the basic action config for coveralls.

```yml
    - name: Coveralls.io Coverage Upload
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```
