### ISSUE TITLE
Documentation Request- Add GitHub Secrets Exmaple

### ISSUE THREAD

**Issue by ericdmoore** [coverallsapp/github-action#53]
I found the JS/TS documentation a bit confusing as how to integrate the GithubActions/ CI.
I really struggled on how to inject the secret: `COVERALLS_REPO_TOKEN`

I could not get the `coveralls github action` to work... not sure if that was my laziness in not wanting to read more on the Github Actions or if there is bug... 

I eventually ended up usiung Github Secrets and the solution involves less magic (AKA GitHub Action Magic)

## NPM Config Example
`package.json` [full reference is below](#referenced-files)
```json
{ 
  "scripts":{
     "test": "nyc ts-node test/index.test.ts",
     "reportCov": "nyc report --reporter=text-lcov | coveralls",
}
```

## GitHub Action File Exmaple
`nodejs.yml` [full reference is below](#referenced-files)
```YAML
name: Build & Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CheckOut Latest
      uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CheckOut Latest
      uses: actions/checkout@v2
    - run: npm ci
    - name: Run Tests + Report Coverage
      env: 
        COVERALLS_SERVICE_NAME: 'GitHub CI'
        COVERALLS_GIT_BRANCH: master
        COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
        NODE_COVERALLS_DEBUG: 0 # or 1 for verbsoe
      run: |
        npm run test && 
        npm run reportCov
```

## Notice

All I needed to know when getting started with GitHub Actions was this line in the `nodejs.yml`
`COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}`

...Just thought I would drop this in your issues so that any future person searching through here might be able to scratch their own itch on how to integrate their `npm run scripts` and `GitHub Actions/ CI`

Anyway nice product and keep up the great work. I am new user, and enjoying it so far.

## Referenced Files
For the files in the wild, the two full blown config files are:

- [Documentation on Adding GitHub Secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository)
- Make Your own URL to add a secret : 
  `https://github.com/{{ org | user }}/{{ repo }}/settings/secrets`
- my live [`package.json`](https://github.com/federalies/dynamoco/blob/master/package.json)
- my live [`nodejs.yml`](https://github.com/federalies/dynamoco/blob/master/.github/workflows/nodejs.yml)
