### ISSUE TITLE
Unexpected input 'flag-name='

### ISSUE THREAD

**Issue by osher** [coverallsapp/github-action#57]
Error:
```
Unexpected input 'flag-name', valid inputs are ['github-token', 'path-to-lcov', 'parallel', 'parallel-finished', 'coveralls-endpoint', 'base-path']
```

Config:
```
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ci-results.os-${{ matrix.os }}.node-${{ matrix.node }}.mongo-${{ matrix.mongo }}.redis-${{ matrix.redis }}
          parallel: true
```

Perhaps I should not use `@master` ? Should I lock it to a specific version?
