### ISSUE TITLE
Support for branches other than master?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [coverallsapp/github-action#61]
Here is my yml that I stole from [here](https://github.com/MarcoIeni/poke-speare/blob/master/.github/workflows/general.yml)

```yml
name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  COVERALLS_GIT_BRANCH: main

jobs:
    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Install stable toolchain
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              override: true
    
          - name: Run cargo-tarpaulin
            uses: actions-rs/tarpaulin@v0.1
            with:
              args: '--ignore-tests --out Lcov'
    
          - name: upload to Coveralls
            if: ${{ github.event_name == 'push' }}
            uses: coverallsapp/github-action@master
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path-to-lcov: './lcov.info
```

I must be doing something dumb because github tells me No jobs were run but I'm not seeing it.
