### ISSUE TITLE
Support relative path for "path-to-lcov" argument

### ISSUE THREAD

**Issue by KeisukeYamashita** [coverallsapp/github-action#70]
## What

When I ran the following step after my test, the step failed

```yaml
- name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./my/path/relative.info
```

with the the error `Lcov: file not found` while if I specify with absolute path, it successes.

```yaml
- name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: /home/runner/work/KeisukeYamashita/myrepo/my/path/relative/lcov.info
```

This is because this line will not use the relative path (https://github.com/coverallsapp/github-action/blob/8cbef1dea373ebce56de0a14c68d6267baa10b44/src/run.ts#L92)
