### ISSUE TITLE
Always getting Error: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

### ISSUE THREAD

**Issue by irverysmart** [coverallsapp/github-action#81]
Trying to use a private repo with the github action using the following .yml:

```
on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install, npm test -- --coverage
      run: |
        npm install
        npm test -- --coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```
this is the exact same .yml provided on https://github.com/coverallsapp/github-action as the "standard example" with         `make test-coverage` swapped for `npm test -- --coverage` (to generate lcov.info). 

i've logged into the website and turned the repository "on" and I see the repository in the "my repos" tab, but still the action always fails with the following:

<img width="748" alt="Screen Shot 2021-05-06 at 3 12 39 AM" src="https://user-images.githubusercontent.com/83751402/117256683-fb177a00-ae18-11eb-9116-b8172311d0cf.png">

I'm kind of stumped, are there some better docs to take a look at or any working examples?
