### ISSUE TITLE
Option to report only summary and not every individual result for parallel runs

### ISSUE THREAD

**Issue by ranocha** [coverallsapp/github-action#85]
We're using GitHub actions to test our Julia project using parallel runs. We use [a setup](https://github.com/trixi-framework/Trixi.jl/blob/c635c6afb1db8b6f6cefc72d1065a111bc730081/.github/workflows/ci.yml#L125-L140) following the [parallel jobs example](https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example). Thus, we get many coverage reports of every individual run, for example in [this PR](https://github.com/trixi-framework/Trixi.jl/pull/574). This is quite annoying, since a commit adding something that is only tested in one of these parallel jobs increases the total amount of code and thus the code coverage of all other individual runs. Moreover, this additional clutter of information even [prevented the use of Coveralls in another project](https://github.com/JuliaCI/PkgBenchmark.jl/pull/125#issuecomment-843003479).

It would be great if there was an option to show only the summary of all runs for parallel jobs.

**Comment by paulrberg** [comment]
Does this GitHub Action help?

https://github.com/dorny/paths-filter

**Comment by ranocha** [comment]
It's description says that it's a

> GitHub Action that enables conditional execution of workflow steps and jobs, based on the files modified by pull request, on a feature branch, or by the recently pushed commits.

That's not what we want. We want to run multiple parallel CI jobs covering different parts of the code and get only the summary of all coverage reports, not the individual ones.

**Comment by oponomarov-pls** [comment]
It's been 4 years without any response. Will we ever this feature request implemented, please? 🙏 

This is how it looks right now:

![Image](https://github.com/user-attachments/assets/25c89f0d-2372-45a7-b491-4de98af724e4)

**Comment by afinetooth** [comment]
Hi @oponomarov-pls et. al. 

I'm sorry for the lack of response here but **this feature has been available since late-2023**.

#### Feature setting:

To avoid receiving a status update/check for every parallel coverage report you've configured in Coveralls, go to the [Repo Settings](https://docs.coveralls.io/app-ui#repo-settings) page for your repo and under **STATUS UPDATES / CHECKS**, **_enable_** the setting: **Limit status updates to overall build?**:

<img width="702" alt="Image" src="https://github.com/user-attachments/assets/f604e9aa-263d-4a3a-923c-0044e33bf51b" />

---

There's always another option as well, which, if you don't need individual parallel reports on your Coveralls build pages, is to give all of your parallel uploads the same [`flag-name` parameter](https://github.com/marketplace/actions/coveralls-github-action#:~:text=flag%2Dname,the%20Coveralls%20UI.) in your CI config.

This tells Coveralls to merge all incoming reports into a single report for each `flag-name`.

#### Example:

Using your example, @oponomarov-pls:

```
    - name: First Coverage Report Upload
      uses: coverallsapp/github-action@v2
      with:
        flag-name: e2e-22.14.0
        parallel: true

[...]

    - name: Second Coverage Report Upload
      uses: coverallsapp/github-action@v2
      with:
        flag-name: e2e-22.14.0
        parallel: true

[...]

    - name: Third Coverage Report Upload
      uses: coverallsapp/github-action@v2
      with:
        flag-name: e2e-22.14.0
        parallel: true
```

That will merge all three uploads into the same, single report at Coveralls called `e2e-22.14.0`, which avoids the issue of parallel builds in the first place. 

This is a common approach when "parallelism" is not  by your design, but introduced by CI parallelization of test runs. Using the same `flag-name` for all parallelized uploads will merge them all into a single report.

In fact, for a matrix build, all you need to do is leave _off_ any dynamic attribute that would distinguish each upload. For example:

```
    - name: Test ${{ matrix.test_number }}
      run: make test-coverage-${{ matrix.test_number }}
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v2
      with:
        flag-name:  test-coverage
        parallel: true
```
